export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const USER_APPLIED_TO_JOB = 'USER_APPLIED_TO_JOB'
export const USER_CREATED_JOB = 'USER_CREATED_JOB'
export const UPDATE_USER = 'UPDATE_USER'
export const RECIVE_NOTIFICATION = 'RECIVE_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'

export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST'
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS'
export const FETCH_JOBS_SUCCESS= 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_REPLACE_SUCCESS= 'FETCH_JOBS_REPLACE_SUCCESS'
export const EMPTY_JOBS= 'EMPTY_JOBS'
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE'
export const SHOW_INFO = 'SHOW_INFO'
export const HIDE_INFO = 'HIDE_INFO'


