export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST'
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS'
export const FETCH_JOBS_SUCCESS= 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE'
export const SHOW_INFO = 'SHOW_INFO'
export const HIDE_INFO = 'HIDE_INFO'


