GET http://localhost:5000/api/v1/jobs
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmI2N2JmNDJiMzg0NTQzYzI0YjIxYzMiLCJuYW1lIjoidmlrdG9yMiIsImlhdCI6MTcyMzIzNTY1NiwiZXhwIjoxNzI1ODI3NjU2fQ.d1wiMx-xpNG_N2m7BFjA2ek0uA2e5sjxU9o6KAewBGs

###



GET http://localhost:5000/api/v1/jobs/669d586f408bc4a95f7041e6


###

DELETE  http://localhost:5000/api/v1/jobs/669d4d17bc193dc1de9e9c88



###

POST http://localhost:5000/api/v1/jobs
Content-Type: application/json

{
  "title": "Job Title",
  "description": "Job Description",
  "numOfWorkers": 5,
  "typeOfPay": "perHour",
  "postedBy":"66b37429823edabfc6ab3fc0"
}


###

GET http://localhost:5000/api/v1/users/all


###

POST http://localhost:5000/api/v1/users/register
Content-Type: application/json

{
  "username":"viktor2",
  "email":"viktor2@mail.com",
  "password":"sifra123"
}

###

GET http://localhost:5000/api/v1/users/66b37444823edabfc6ab3fc4

###


POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
    "username":"viktor2",
  "password":"sifra123"
}
