GET http://localhost:5000/api/v1/jobs
//authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmI2N2JmNDJiMzg0NTQzYzI0YjIxYzMiLCJuYW1lIjoidmlrdG9yMiIsImlhdCI6MTcyMzIzNzUxMSwiZXhwIjoxNzI1ODI5NTExfQ.d_wGNkwWmAIwcTZk2Ap5kQ5jPOirg1WdtYAOPM7TWfk

###



GET http://localhost:5000/api/v1/jobs/669d586f408bc4a95f7041e6


###

DELETE  http://localhost:5000/api/v1/jobs/669d4d17bc193dc1de9e9c88



###

POST http://localhost:5000/api/v1/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmI2N2JmNDJiMzg0NTQzYzI0YjIxYzMiLCJuYW1lIjoidmlrdG9yMiIsImlhdCI6MTcyMzIzODY4NCwiZXhwIjoxNzI1ODMwNjg0fQ.sn0Hp2Pvns_8cvCQSwQRXWHvQvhQV_nQ-ZllKiGSN5Q

{
  "title": "Job 4",
  "description": "Job Description"
}


###

GET http://localhost:5000/api/v1/users/all


###

POST http://localhost:5000/api/v1/users/register
Content-Type: application/json

{
  "username":"viktor2",
  "email":"viktor2@mail.com",
  "password":"sifra123"
}

###

GET http://localhost:5000/api/v1/users/66b37444823edabfc6ab3fc4

###


POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
    "username":"viktor2",
  "password":"sifra123"
}
